name: Validate the-mod-index
description: Validate the index.json and all manifest.json files for ReviversMC/the-mod-index styled indexes.
runs:
  using: composite
  steps:
    - name: Checkout the action repo
      uses: actions/checkout@v3
      with:
        repository: ReviversMC/the-mod-index-validation
    - name: Checkout the repo to check
      uses: actions/checkout@v3
      with:
        path: repo-to-check
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: "17"
    - name: ShadowJar validator
      shell: bash
      run: ./gradlew shadowJar
    - name: Run the-mod-index validator
      shell: bash
      run: java -jar build/libs/*.jar repo-to-check/mods
