name: Validate the-mod-index
description: Validate the index.json and all manifest.json files for ReviversMC/the-mod-index styled indexes.
inputs:
  repoUrl:
    description: The URL of the repository to validate. Defaults to ReviversMC/the-mod-index.
    required: false
runs:
  using: composite
  steps:
    - name: Checkout the repo. Ensure this is the action repo, not the consumer repo!
      uses: actions/checkout@v3
      with:
        repository: ReviversMC/the-mod-index-validation
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: "17"
    - name: ShadowJar validator
      shell: bash
      run: ./gradlew shadowJar
    - name: Run the-mod-index validator
      shell: bash
      run: java -jar build/libs/*.jar ${{ inputs.repoUrl }}
